CREATE TABLE GOODS (
	CODE VARCHAR(250) PRIMARY KEY,
	NAME VARCHAR(250),
	price INT,
	stock INT,
	category VARCHAR(250)
);

CREATE TABLE `ORDER` (
	NO INT PRIMARY KEY,
	customer VARCHAR(250),
	productcode VARCHAR(250),
	amount INT,
	ISCANCELED TINYINT(1) DEFAULT 0
);
ALTER TABLE `ORDER` ADD FOREIGN KEY(productcode) REFERENCES goods(CODE);

-- UPDATE goods SET stock=30 WHERE (SELECT productcode FROM order WHERE NO=1);

DELETE FROM goods;
DELETE FROM `order`;

DROP TABLE `order`;
DROP TABLE goods;
